# Generated by Django 5.2.3 on 2025-06-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("apps", "Apps"),
                    ("data science", "Data Science"),
                    ("visualization", "Visualization"),
                ],
                default="visualization",
                max_length=50,
            ),
        ),
    ]
