# Generated by Django 5.2.3 on 2025-07-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_project_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[("apps", "Apps"), ("projects", "Projects")],
                default="apps",
                max_length=50,
            ),
        ),
    ]
