# Generated by Django 5.2.3 on 2026-02-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_project_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("apps", "Apps"),
                    ("projects", "Projects"),
                    ("photos", "Photos"),
                ],
                default="apps",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
